color0 #404040
color1 #f44747
color2 #6a9955
color3 #dcdcaa
color4 #569cd6
color5 #c586c0
color6 #4ec9b0
color7 #d4d4d4
color8 #808080
color9 #d16969
color10 #b5cea8
color11 #d7ba7d
color12 #9cdcfe
color13 #646695
color14 #4fc1ff
color15 #d4d4d4

cursor                #aeafad
cursor_text_color     #1f1f1f
background            #1f1f1f
foreground            #d4d4d4
selection_foreground  #d4d4d4
selection_background  #264f78
active_border_color   #569cd6
inactive_border_color #252526
url_color             #569cd6

active_tab_foreground   #1f1f1f
active_tab_background   #569cd6
inactive_tab_foreground #808080
inactive_tab_background #252526
cursor_trail_color      #808080
