#!/bin/bash 
export TERMINAL=kitty

picom --config ~/.config/picom/picom.conf --experimental-backends &
$HOME/.config/polybar/launch.sh &
nm-applet &
blueman-applet &
nitrogen --restore &
devilspie2 &
~/.local/bin/set-display &
~/.local/bin/setup-touchpad &
~/.local/bin/set-keyboard &
