#!/bin/bash 
export TERMINAL=kitty

picom --config ~/.config/picom/picom.conf --experimental-backends &

nm-applet &
protonvpn-app &
devilspie2 &

~/.local/bin/set-display &
~/.local/bin/setup-touchpad &
~/.local/bin/set-keyboard &
~/.local/bin/watch-power &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
